trigger:
  - master
pool:
  vmImage: 'Ubuntu-16.04'
steps:
  - task: AzureCLI@2
    inputs:
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'upgrades=$(az aks get-upgrades -g rg-kubernetes-01 -n k8s-demo --query ''controlPlaneProfile.upgrades[?isPreview==null].kubernetesVersion'')'